# Import play books
- name: Install Kubernetes Dependencies in all Servers
  import_playbook: kube-dependencies.yml
- name: Initialize Kubernetes Master in Master Server
  import_playbook: master-cluster.yml
- name: Get Token from Master and join Workers
  import_playbook: workers-cluster.yml